#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times and if no argument dispaly Usage: filename {IP_ADDRESS}.

if [ $# -eq 0 ]
then
  echo "Usage: $0 {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
